# Only spawn workflows for MRs or protected branches
workflow:
  rules:
  - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"'
    when: never
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED != "true"
    when: never
  - when: always


stages:
- validate
- dependencies
- test
- lint


include:
# Jobs for building all the dependencies with Spack
- local: ci/dependencies/.gitlab-ci.yml


variables:
  # Add a transfer progress bar for artifacts
  TRANSFER_METER_FREQUENCY: 2s

  # Use fastzip to package caches and artifacts
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: default
  CACHE_COMPRESSION_LEVEL: fastest


default:
  # Most jobs can be interrupted and should be retried if failed for mysterious reasons
  interruptible: true
  retry:
    max: 2
    when:
    - unknown_failure
    - api_failure
    - runner_system_failure

  # By default, use a Docker runner with a late-model CI image
  tags: [docker]
  image: registry.gitlab.com/hpctoolkit/ci-images/ubuntu20.04:latest


# Pre-commit linting passes must pass for the pipeline to succeed
precommit:
  stage: lint
  tags: [docker, linux/amd64]
  image: registry.gitlab.com/hpctoolkit/ci-images/selfcheck:amd64
  needs: []
  cache:
    key: precommit
    paths:
    - .pc-cache/
  script:
  - mkdir -p .pc-cache/ ~/.cache/
  - ln -s $(realpath .pc-cache/) ~/.cache/pre-commit
  - pre-commit run --all-files || { git diff | tee fixup.patch && exit 1; }
  artifacts:
    paths:
    - fixup.patch


# The Autogoo for the HEAD commit (at least) must be in-sync before we build
autoreconf:
  stage: validate
  tags: [docker, linux/amd64]
  image: registry.gitlab.com/hpctoolkit/ci-images/hpct-devtools:amd64
  needs: []
  script:
  - ./autogen > autogen.log
  - git status --porcelain=v1 --untracked-files=no > changes || exit $?
  - |
    if test -s changes; then
      echo "== CHANGES DETECTED, running git diff..."
      git diff | tee fixup.patch
      echo "== AUTOGOO OUT-OF-SYNC, see patch above and in fixup.patch for details"
      exit 1
    fi
  artifacts:
    when: always
    paths:
    - autogen.log
    - fixup.patch


# Also check that the Autogoo is in-sync for all commits that will be merged,
# but only if merged results pipelines are enabled.
autoreconf check:
  stage: lint
  tags: [docker, linux/amd64]
  image: registry.gitlab.com/hpctoolkit/ci-images/hpct-devtools:amd64
  needs:
  - autoreconf

  allow_failure: true
  variables:
    GIT_DEPTH: 100
  rules:
  - if: $CI_MERGE_REQUEST_TARGET_BRANCH_SHA
  script:
  - TARG="$(git show --no-patch --pretty=reference $CI_MERGE_REQUEST_TARGET_BRANCH_SHA)"
  - SRC="$(git show --no-patch --pretty=reference $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA)"
  - MERGE="$(git show --no-patch --pretty=reference HEAD)"
  - echo "Checking commit range $TARG..$SRC + $MERGE"
  - git rev-list --topo-order --reverse HEAD ^"$CI_MERGE_REQUEST_TARGET_BRANCH_SHA" > revs
  - |
    while read rev; do
      echo
      echo "== Checking $(git show --no-patch --pretty=reference $rev)" | tee -a autogen.log
      git checkout --force "$rev" || exit $?
      git clean -fxd || exit $?
      ./autogen >> autogen.log || exit $?
      git status --porcelain=v1 --untracked-files=no > changes || exit $?
      if test -s changes; then
        echo "== CHANGES DETECTED, running git diff..."
        git diff | tee fixup.patch
        echo "== AUTOGOO OUT-OF-SYNC, see patch above and in fixup.patch for details"
        echo "== First noticed desynchronization in commit:"
        git show --no-patch --pretty=medium $rev
        exit 1
      fi
    done < revs
  artifacts:
    when: always
    paths:
    - autogen.log
    - fixup.patch

# Many jobs require Spack to function. This is the common setup pieces.
# Note that Spack may shift SHA's between jobs.
.spack:
  cache: &cache_spack
    key: spack
    when: always
    paths: [.spack.git]
  before_script:
  - echo -e "\e[0Ksection_start:`date +%s`:spack_clone_init[collapsed=true]\r\e[0KSpack update and initialization"
  - - export SPACK_ROOT="$(realpath .spack)"
    - ci/dependencies/spack-init.sh
    - source "$SPACK_ROOT"/share/spack/setup-env.sh
  - echo -e "\e[0Ksection_end:`date +%s`:spack_clone_init\r\e[0K"

# Build jobs require a working Spack with access to the buildcache. This (very long) job handles all
# the common setup pieces that go into that.
.buildcache-job:
  cache:
  - !reference [.spack, cache]
  - &bcjob_cache1
    key: bcjob-$CI_JOB_IMAGE
    when: always
    paths:
    - .apt-cache/
    - .pip-cache/
    - .spack-bincache/
  - &bcjob_cache2
    key: bcjob-$CI_JOB_IMAGE-$JOB_CC
    when: always
    paths:
    - .ccache/

  before_script:
  # Make sure we have the basic set of utilities required to launch Spack and build stuff
  - ci/scripts/ensure-present.sh make git curl cc file patchelf python3 py:boto3 py:clingo ${JOB_CC:+ccache}

  # Unpack and instantiate Spack here
  - !reference [.spack, before_script]

  - echo -e "\e[0Ksection_start:`date +%s`:spack_buildcache_config[collapsed=true]\r\e[0KSpack buildcache configuration"
  - - ci/dependencies/spack-bc-downstream.sh
    # Configure the local binary cache to cache binaries
    - spack config --scope site add "config:binary_cache_root:$CI_PROJECT_DIR/.spack-bincache/"
    # Make sure Spack has a GCC available. Oddly enough, this command will run `spack compiler find` internally,
    # but only if needed.
    - spack compiler info gcc
    # Mark down the OS and arch, as used in the concretized environment paths
    - os="$(spack arch --operating-system)"
    - |
      case "$(spack arch --generic-target)" in
      x86_64*) arch=amd64; ;;
      aarch64) arch=arm64; ;;
      ppc64le) arch=ppc64le; ;;
      *) echo "Unknown generic target: $(spack arch --generic-target)"; exit 1; ;;
      esac
    - concrete=/c/$os/$arch/
  - echo -e "\e[0Ksection_end:`date +%s`:spack_buildcache_config\r\e[0K"

  - if test -n "$JOB_CC"; then
  - - echo -e "\e[0Ksection_start:`date +%s`:ccache_init[collapsed=true]\r\e[0KCompiler and ccache initialization"
    # Derive the CC/CXX from the JOB_CC shorthand
    - |
      test -z "$JOB_CC" || case "$JOB_CC" in
      # Rocky/Fedora/SUSE form, which don't ship multiple GCCs
      gcc=*)
        export CC=gcc CXX=g++
        ;;
      # Debian/Ubuntu form, which ships multiple GCCs
      gcc-*)
        export CC=gcc-"${JOB_CC##gcc-}" CXX=g++-"${JOB_CC##gcc-}"
        ;;
      *)
        echo "Invalid compiler shorthand: $JOB_CC"
        exit 1
        ;;
      esac
    - test -z "$JOB_CC" || "$CC" --version
    - test -z "$JOB_CC" || "$CXX" --version
    # Initialize ccache
    - export CCACHE_DIR="$(realpath .ccache/)" CCACHE_BASEDIR="$CI_PROJECT_DIR"
    - ccache --zero-stats
    # Replace CC/CXX with ccache'd versions
    - mkdir .ccache-bin/
    - if test -n "$JOB_CC"; then ln -s "$(command -pv ccache)" .ccache-bin/"$CC" && export CC="$(realpath .ccache-bin)/$CC" || exit $?; fi
    - if test -n "$JOB_CC"; then ln -s "$(command -pv ccache)" .ccache-bin/"$CXX" && export CXX="$(realpath .ccache-bin)/$CXX" || exit $?; fi
    - echo -e "\e[0Ksection_end:`date +%s`:ccache_init\r\e[0K"
  - fi

  - &postjob
    - ci/scripts/network-stats.sh .netstats.txt

  after_script:
  # Report statistics on how much ccache helped in this job
  - CCACHE_DIR="$(realpath .ccache/)" ccache --show-stats

.buildcache-job-derivative:
  extends: .buildcache-job
  cache:
  - !reference [.spack, cache]
  - <<: *bcjob_cache1
    key: bcjob-$BASE_IMAGE
  - *bcjob_cache2

# Build many versions of the codebase, to ensure all the various compilations work
'buildmany.amd64: [*]':
  stage: test
  extends: .buildcache-job
  tags: [docker, linux/$ARCH]
  image: registry.gitlab.com/hpctoolkit/ci-images/$IMAGE:$ARCH
  variables:
    ARCH: amd64
  parallel:
    matrix:
    - IMAGE: leap15
      JOB_CC: gcc=7

    - IMAGE: almalinux8
      JOB_CC: gcc=8

    # XXX: Disabled due to Spack-related issues
    # - IMAGE: centos7
    #   JOB_CC: gcc=8

    - IMAGE: ubuntu20.04
      JOB_CC: [gcc-9, gcc-10, gcc-11.3.0]

    - IMAGE: fedora36
      JOB_CC: gcc=12

  needs:
  - job: autoreconf
    artifacts: false
  - generate_deps.amd64
  - build_deps.amd64

  script:
  # Run the build script for a wide sweep of configurations. Use some Python to help.
  # The matrix of configurations is chosen to test cases that are most likely to trigger
  # configuration or compile errors, by enabling all features and removing one at a time.
  # The exception is the variant `+~debug`, which is always swept completely.
  - >-
    python3 -m ci.buildfe -l "logs/$CI_JOB_NAME/latest" -a install -a check-install
    "ci/dependencies/latest;ci/dependencies/latest/$concrete"
    --spack-args='--use-buildcache=only --no-check-signature --fail-fast' --ccache-stats
    -s '+mpi +papi +opencl ~cuda~rocm~level0'
    -s '~mpi +papi +opencl ~cuda~rocm~level0'
    -s '+mpi ~papi +opencl ~cuda~rocm~level0'
    -s '+mpi +papi ~opencl ~cuda~rocm~level0'
  - >-
    python3 -m ci.buildfe -l "logs/$CI_JOB_NAME/minimum" -a install -a check-install
    "ci/dependencies/minimum;ci/dependencies/minimum/$concrete"
    --spack-args='--use-buildcache=only --no-check-signature --fail-fast' --ccache-stats
    -s '+mpi +papi +opencl ~cuda~rocm~level0'
    -s '~mpi +papi +opencl ~cuda~rocm~level0'
    -s '+mpi ~papi +opencl ~cuda~rocm~level0'
    -s '+mpi +papi ~opencl ~cuda~rocm~level0'
  - *postjob

  artifacts:
    paths:
    - logs/
    when: always

'buildmany.amd64: [+cuda]':
  extends: .buildcache-job-derivative
  image: nvcr.io/nvidia/cuda:$CUDA-devel-ubuntu20.04
  services:
  - name: registry.gitlab.com/hpctoolkit/ci-images/ubuntu20.04-bundles:amd64
    alias: bundleserver
  tags: [docker, linux/amd64]
  variables:
    JOB_CC: gcc-9
    BASE_IMAGE: registry.gitlab.com/hpctoolkit/ci-images/ubuntu20.04:amd64
  parallel:
    matrix:
    - CUDA: [11.7.1]

  needs:
  - job: autoreconf
    artifacts: false
  - generate_deps.amd64
  - build_deps.amd64

  script:
  # Pull CUDA from the image itself
  - echo '--with-cuda=/usr/local/cuda' > img-config
  # Run the build script for a wide sweep of configurations. Use some Python to help.
  # See the `buildmany: [~gpus]` script for details on this design
  - >-
    python3 -m ci.buildfe -l "logs/$CI_JOB_NAME/latest" -a install -a check-install
    img-config "ci/dependencies/latest;ci/dependencies/latest/$concrete"
    --spack-args='--use-buildcache=only --no-check-signature --fail-fast' --ccache-stats
    -s '+mpi +papi +opencl +cuda~rocm~level0'
    -s '~mpi +papi +opencl +cuda~rocm~level0'
    -s '+mpi ~papi +opencl +cuda~rocm~level0'
    -s '+mpi +papi ~opencl +cuda~rocm~level0'
  - >-
    python3 -m ci.buildfe -l "logs/$CI_JOB_NAME/minimum" -a install -a check-install
    img-config "ci/dependencies/minimum;ci/dependencies/minimum/$concrete"
    --spack-args='--use-buildcache=only --no-check-signature --fail-fast' --ccache-stats
    -s '+mpi +papi +opencl +cuda~rocm~level0'
    -s '~mpi +papi +opencl +cuda~rocm~level0'
    -s '+mpi ~papi +opencl +cuda~rocm~level0'
    -s '+mpi +papi ~opencl +cuda~rocm~level0'
  - *postjob

  artifacts:
    paths:
    - logs/
    when: always


'buildmany.amd64: [+rocm]':
  extends: .buildcache-job-derivative
  image: docker.io/rocm/dev-ubuntu-20.04:$ROCM
  services:
  - name: registry.gitlab.com/hpctoolkit/ci-images/ubuntu20.04-bundles:amd64
    alias: bundleserver
  tags: [docker, linux/amd64]
  variables:
    JOB_CC: gcc-9
    BASE_IMAGE: registry.gitlab.com/hpctoolkit/ci-images/ubuntu20.04:amd64
  parallel:
    matrix:
    - ROCM: [5.2.3]

  needs:
  - job: autoreconf
    artifacts: false
  - generate_deps.amd64
  - build_deps.amd64

  script:
  # Pull ROCm from the image itself
  - echo '--with-rocm=/opt/rocm' > img-config
  # Run the build script for a wide sweep of configurations. Use some Python to help.
  # See the `buildmany: [~gpus]` script for details on this design
  - >-
    python3 -m ci.buildfe -l "logs/$CI_JOB_NAME/latest" -a install -a check-install
    img-config "ci/dependencies/latest;ci/dependencies/latest/$concrete"
    --spack-args='--use-buildcache=only --no-check-signature --fail-fast' --ccache-stats
    -s '+mpi +papi +opencl ~cuda+rocm~level0'
    -s '~mpi +papi +opencl ~cuda+rocm~level0'
    -s '+mpi ~papi +opencl ~cuda+rocm~level0'
    -s '+mpi +papi ~opencl ~cuda+rocm~level0'
  - >-
    python3 -m ci.buildfe -l "logs/$CI_JOB_NAME/minimum" -a install -a check-install
    img-config "ci/dependencies/minimum;ci/dependencies/minimum/$concrete"
    --spack-args='--use-buildcache=only --no-check-signature --fail-fast' --ccache-stats
    -s '+mpi +papi +opencl ~cuda+rocm~level0'
    -s '~mpi +papi +opencl ~cuda+rocm~level0'
    -s '+mpi ~papi +opencl ~cuda+rocm~level0'
    -s '+mpi +papi ~opencl ~cuda+rocm~level0'
  - *postjob

  artifacts:
    paths:
    - logs/
    when: always


'buildmany.amd64: [+level0]':
  extends: .buildcache-job-derivative
  image: docker.io/intel/oneapi-basekit:$ONEAPI-devel-ubuntu20.04
  services:
  - name: registry.gitlab.com/hpctoolkit/ci-images/ubuntu20.04-bundles:amd64
    alias: bundleserver
  tags: [docker, linux/amd64]
  variables:
    JOB_CC: gcc-9
    BASE_IMAGE: registry.gitlab.com/hpctoolkit/ci-images/ubuntu20.04:amd64
  parallel:
    matrix:
    - ONEAPI: ['2022.2']

  needs:
  - job: autoreconf
    artifacts: false
  - generate_deps.amd64
  - build_deps.amd64

  before_script:
  # The base Intel image has some extra elements on the PATH, make sure /usr/local/bin takes precdence
  - export PATH=/usr/local/bin:"$PATH"
  - !reference [.buildcache-job, before_script]
  script:
  # Pull Level 0 (part of OneAPI) from the image itself
  - echo '--with-level0=/usr' > img-config
  # Run the build script for a wide sweep of configurations. Use some Python to help.
  # See the `buildmany: [~gpus]` script for details on this design
  - >-
    python3 -m ci.buildfe -l "logs/$CI_JOB_NAME/latest" -a install -a check-install
    img-config "ci/dependencies/latest;ci/dependencies/latest/$concrete"
    --spack-args='--use-buildcache=only --no-check-signature --fail-fast' --ccache-stats
    -s '+mpi +papi +opencl ~cuda~rocm+level0'
    -s '~mpi +papi +opencl ~cuda~rocm+level0'
    -s '+mpi ~papi +opencl ~cuda~rocm+level0'
    -s '+mpi +papi ~opencl ~cuda~rocm+level0'
  - >-
    python3 -m ci.buildfe -l "logs/$CI_JOB_NAME/minimum" -a install -a check-install
    img-config "ci/dependencies/minimum;ci/dependencies/minimum/$concrete"
    --spack-args='--use-buildcache=only --no-check-signature --fail-fast' --ccache-stats
    -s '+mpi +papi +opencl ~cuda~rocm+level0'
    -s '~mpi +papi +opencl ~cuda~rocm+level0'
    -s '+mpi ~papi +opencl ~cuda~rocm+level0'
    -s '+mpi +papi ~opencl ~cuda~rocm+level0'
  - *postjob

  artifacts:
    paths:
    - logs/
    when: always


# Build single versions of the codebase and run unit tests through `make check`
check.amd64:
  stage: test
  extends: .buildcache-job
  tags: [docker, linux/$ARCH]
  image: registry.gitlab.com/hpctoolkit/ci-images/$IMAGE:$ARCH
  variables:
    ARCH: amd64
  parallel:
    matrix:
    - IMAGE: ubuntu20.04
      JOB_CC: gcc-10
      SPEC:
      - +mpi +debug +papi ~opencl ~cuda ~rocm ~level0
      - +mpi +debug ~papi ~opencl ~cuda ~rocm ~level0

  needs:
  - job: autoreconf
    artifacts: false
  - generate_deps.amd64
  - build_deps.amd64

  script:
  # Run the build script for the configuration of interest. Use some Python to help.
  - >-
    python3 -m ci.buildfe -l "logs/$CI_JOB_NAME/latest" -a test
    "ci/dependencies/latest;ci/dependencies/latest/$concrete"
    --spack-args='--use-buildcache=only --no-check-signature --fail-fast' --ccache-stats
    -1 -s "$SPEC"
  - *postjob

  artifacts:
    paths:
    - logs/
    when: always

check.arm64:
  extends: check.amd64
  variables:
    ARCH: arm64

  needs:
  - job: autoreconf
    artifacts: false
  - generate_deps.arm64
  - build_deps.arm64


# Check that the Spack recipe for @develop is sufficiently up-to-date to compile this branch.
# Failures are allowed so that if the dependencies or build flags shift, we are made aware (by a
# big orange exclaimation point) but not blocked by upstream Spack.
spack install:
  stage: lint
  extends: .buildcache-job
  tags: [docker, linux/$ARCH]
  image: registry.gitlab.com/hpctoolkit/ci-images/ubuntu20.04:$ARCH
  parallel:
    matrix:
    - ARCH: [amd64]

  allow_failure: true
  script:
  # Spack out a representative HPCToolkit. All dependencies should be in the buildcache.
  # TODO: Expand this list a bit sometime to better represent what we want to ensure works
  - HPCTOOLKIT="hpctoolkit @git.${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA:-${CI_COMMIT_SHA}}=develop"
  - >-
    spack install --no-check-signature --fail-fast --use-buildcache=package:never,dependencies:only
    "$HPCTOOLKIT ~viewer ~mpi ~debug +papi +opencl ~cuda ~rocm ~level_zero"
    "$HPCTOOLKIT ~viewer ~mpi ~debug ~papi +opencl ~cuda ~rocm ~level_zero"
