specs:
# The ./dev scriptsuit requires Python 3.10. Needs to be specified here for the autogen image.
- 'python @3.10:'

mirrors:
  # Reuse from the Spack public buildcache when possible
  develop: 'https://binaries.spack.io/develop'

concretizer:
  # Reuse everything, including the roots
  reuse: true

packages:
  all:
    # NB: These requirements must be anchor-copied to all packages with custom requires
    require:
    # Only concretize for certain generic architectures
    - &target {any_of: ['target=:x86_64_v3', 'target=:aarch64']}
    # Disallow infinity versions, we only support full "point" releases
    - &noinf '@:99999999'

  mpi:
    # MPI in CI is OpenMPI
    require: openmpi

  openmpi:
    require:
    - *target
    - *noinf
    # 4.1.5 is the first version that supports OMPI_ALLOW_RUN_AS_ROOT
    - '@4.1.5:'

  xz:
    require:
    - *target
    - *noinf
    # FIXME: Temporary requirement to work around a bad Spack concretization
    # See https://github.com/spack/spack/issues/37237
    - 'libs=shared'

config:
  template_dirs: [templates]

container:
  # Stripping makes the images *larger* due to a Spack bug. We also want debug
  # info for debugging crashes. Don't strip.
  strip: false

  # Use a custom template that handles a few nits
  template: spins/base.Dockerfile

dev:
  features:
    cuda: false
    rocm: false
    level0: false
    gtpin: false
    opencl: true
    python: true
    papi: both
    mpi: true
