ci:
  target: gitlab

  pipeline-gen:
  - noop-job:
      # Marking no-op jobs with these tag ensures the pipeline gets purged by the MLP
      tags: [noop-job]
      before_script:: []

  - submapping:
    - match: ['os=fedora37']
      build-job:
        image:
          name: ghcr.io/spack/fedora37:latest
          entrypoint: ['spack-env']
    - match: ['os=opensuse15']
      build-job:
        image:
          name: ghcr.io/spack/leap15:latest
          entrypoint: ['spack-env']
    - match: ['os=almalinux8']
      build-job:
        image:
          name: ghcr.io/spack/almalinux8:latest
          entrypoint: ['spack-env']
    - match: ['os=ubuntu20.04']
      build-job:
        image:
          name: ghcr.io/spack/ubuntu-focal:latest
          entrypoint: ['spack-env']

  - submapping:
    - match: ['target=:x86_64_v3']
      build-job:
        tags: [saas-linux-small-amd64]
        variables:
          ARCH: amd64
    - match: ['target=:aarch64']
      build-job:
        tags: [rice-linux-small-arm64]
        variables:
          ARCH: arm64

  - build-job:
      cache:
      - key: spack-install-$CI_JOB_IMAGE
        paths: [.spack-install/]
      resource_group: bcbuild-$SPACK_JOB_SPEC_DAG_HASH

      script:
      - spack --version

      # Configure Spack for building relocatable packages
      - spack config add 'config:install_tree:padded_length:100'

      # Configure the (cached) install tree, and remove the to-be-installed package
      - spack config add 'config:install_tree:root:${CI_PROJECT_DIR}/.spack-install/'
      - spack uninstall -yf "$SPACK_JOB_SPEC_PKG_NAME /$SPACK_JOB_SPEC_DAG_HASH" || true

      # Load the Spack shell support
      - . "$SPACK_ROOT"/share/spack/setup-env.sh

  - reindex-job:
      image:
        name: ghcr.io/spack/ubuntu-focal:latest
        entrypoint: ['spack-env']
      resource_group: bcindex-$CI_COMMIT_REF_SLUG

  - any-job:
      before_script:
      # Install the buildcache mirrors
      - spack config add -f "$SBCACHE_YAML"
