packages:
  all:
    # NB: These requirements must be anchor-copied to all packages with custom requires
    require:
    # Only concretize for certain generic architectures
    - &target {any_of: ['target=:x86_64_v3', 'target=:aarch64']}
    # Disallow infinity versions, we only support full "point" releases
    - &noinf '@:99999999'

    providers:
      # Use OpenMPI for MPI in CI
      mpi: [openmpi]

  mpi:
    # No, really use OpenMPI for MPI in CI
    require:
    - *target
    - *noinf
    - 'openmpi'

  openmpi:
    require:
    - *target
    - *noinf
    # 4.1.5 is the first version that supports OMPI_ALLOW_RUN_AS_ROOT
    - '@4.1.5:'

  xz:
    require:
    - *target
    - *noinf
    # FIXME: Temporary requirement to work around a bad Spack concretization
    # See https://github.com/spack/spack/issues/37237
    - 'libs=shared'
